django-portfolio-main_lkc/mywebapp/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('teacher/', views.teacher, name='teacher'),
    path('blog/', views.blog, name='blog'),

    
]

django-portfolio-main_lkc/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mywebapp.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django-portfolio-main_lkc/Student/models.py
from django.db import models
from ctypes import addressof
from distutils.command.upload import upload
from email.mime import image
from django.utils.html import format_html
from django.contrib.auth.models import User
# Create your models here.

class Student(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='student_image')
    phone_number = models.CharField(max_length=50)
    email= models.EmailField(max_length=50)
    studentID = models.CharField(max_length=10)
    address = models.CharField(max_length=50, null=True)

    def show_image_pic(self):
        if self.image:
            return format_html('<img src="%s" height="50px">' % self.image.url)
        return 'NULL'
    show_image_pic.allow_tags = True




    def __str__(self):
        return self.user.username

django-portfolio-main_lkc/Techerts/models.py
from django.db import models
from ctypes import addressof
from distutils.command.upload import upload
import email
from email.mime import image
from django.utils.html import format_html
from django.contrib.auth.models import User
# Create your models here.

class Techerts(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='student_image')
    phone_number = models.CharField(max_length=50)
    email= models.EmailField(max_length=50)
    studentID = models.CharField(max_length=10)
    address = models.CharField(max_length=50, null=True)

    def show_image_pic(self):
        if self.image:
            return format_html('<img src="%s" height="50px">' % self.image.url)
        return 'NULL'
    show_image_pic.allow_tags = True




    def __str__(self):
        return self.user.username

django-portfolio-main_lkc/mywebapp/models.py
from django.db import models
from ctypes import addressof
from distutils.command.upload import upload
import email
from email.mime import image
from django.utils.html import format_html
from django.contrib.auth.models import User
# HOME SECTION

class Home(models.Model):
    name = models.CharField(max_length=20)
    greetings_1 = models.CharField(max_length=5)
    greetings_2 = models.CharField(max_length=5)
    picture = models.ImageField(upload_to='picture/')
    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ABOUT SECTION

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career


class Profile(models.Model):
    about = models.ForeignKey(About,
                                on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)



# SKILLS SECTION

class Category(models.Model):
    

    updated = models.ImageField(upload_to='pictures/')
    name = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'Skill'
        verbose_name_plural = 'Skills'

    def __str__(self):
        return self.name

class Skills(models.Model):
    category = models.ForeignKey(Category,
                                on_delete=models.CASCADE)
    skill_name = models.ImageField(upload_to='picture/')



# PORTFOLIO SECTION

class Techer(models.Model):
    image = models.ImageField(upload_to='portfolio/')
    link = models.CharField(max_length=200)

    def __str__(self):
        return f'Techer {self.id}'


class Techert(models.Model):
    image = models.ImageField(upload_to='pictures/')
    link = models.CharField(max_length=200)

    def __str__(self):
        return f'Techert {self.id}'

class Blog(models.Model):
    image = models.ImageField(upload_to='picture/')
    

    def __str__(self):
        return f'Blog {self.id}'


# class Student(models.Model):
#     user = models.ForeignKey(User,on_delete=models.CASCADE)
#     first_name = models.CharField(max_length=50)
#     last_name = models.CharField(max_length=50)
#     image = models.ImageField(upload_to='student_image')
#     phone_number = models.CharField(max_length=50)
#     email= models.EmailField(max_length=50)
#     studentID = models.CharField(max_length=10)
#     address = models.CharField(max_length=50, null=True)

#     def show_image_pic(self):
#         if self.image:
#             return format_html('<img src="%s" height="50px">' % self.image.url)
#         return 'NULL'
#     show_image_pic.allow_tags = True




#     def __str__(self):
#         return self.user.username

django-portfolio-main_lkc/Student/views.py
from django.shortcuts import render
from unicodedata import name
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from .models import Student
# Create your views here.

def dashboard(request):
    
    student = Student.objects.all().order_by('-pk')
    
    return render(request, 'dashboard.html', {'student':student})

django-portfolio-main_lkc/Techerts/views.py
from django.shortcuts import render
from unicodedata import name
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from .models import Techerts


# Create your views here.
def dashboard(request):
    
    techer = Techerts.objects.all().order_by('-pk')
    
    return render(request, 'dashboard.html', {'techer':techer})

    

django-portfolio-main_lkc/mywebapp/views.py
from django.shortcuts import render
from unicodedata import name
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate
from .models import  Home,About, Profile, Category, Skills, Techer,Techert,Blog

def index(request):

    # Home
    
    
    return render(request, 'index.html')
    # About
def about(request):
    about = About.objects.latest('updated')

    profiles = Profile.objects.filter(about=about)
    return render(request, 'about.html',{'about':about,'profiles':profiles})
    # Skills
def teacher(request):    
    # Portfolio
    portfolios = Techer.objects.all()
#techer2

    portfolior = Techert.objects.all()
    return render(request, 'teacher.html',{'portfolios':portfolios,'portfolior':portfolior})
#blog post
def blog(request):

    blogs = Blog.objects.all()
    categories = Category.objects.all()

    return render(request, 'blog.html',{'blogs':blogs,'categories':categories})

# def dashboard(request):
    
#     student = Student.objects.all().order_by('-pk')
    
#     return render(request, 'dashboard.html', {'student':student})

django-portfolio-main_lkc/mywebapp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    
            <section class="section-1 ">
                <div class="p-text" id="about">
                    <h1 class="h-t">ກ່ຽວກັບເຮົາ</h1>
                </div>
                <div class="row ">
                    <div class="pray " data-aos="fade-right ">
                        <img src="{{ about.profile_img.url }}">
                    </div>
                    <div class="panel text-left " data-aos="fade-left ">
                        <h1 class="pt-4 ">{{ about.heading }}</h1>
                        <p>
                            {{ about.description }}
                        </p>
                    </div>
                </div>
            </section>
            <div class="b-dy">
                <div class="p-text test">
                    <h1 class="h-t" id="t-hid">ເປົ້າໝາຍຂອງການສຶກສາ</h1>
                    <div class="container2">
                        <div class="box">
                            <div class="textq">
                                <p>ປູກຝັງຂອງວິສະວະກອນໄອທີຜູ້ທີ່ຈະຂັບເຄື່ອນວົງການໄອທີໃນອະນາຄົດຂອງ ສປປ ລາວ</p>
                            </div>
                        </div>
                        <div class="box">
                            <div class="textq">
                                <p>ກາຍໄປນັກວິສະວະກອນຊອບແວ (ນັກຂຽນໂປຣແກມ), ວິສະວະກອນຄອມພິວເຕີ, ແລະ ວິສະວະກອນລະບົບເຄື່ອຂ່າຍ</p>
                            </div>
                        </div>
                        <div class="box">
                            <div class="textq">
                                <p>ປູກຝັງຜູ້ມີພອນສະຫວັນດ້ວຍການແຂ່ງຂັນລະດັບສາກົນ</p>
                            </div>
                        </div>
                    </div>
                </div>
    
                <div class="p-text">
                    <h1 class="h-t h2">ວິຊາຫຼັກ</h1>
                    <div class="container2">
                        <div class="c-lom">
                            <div class="box2">
                                <div class="content2">
                                    <div class="text">
                                        <p>ພາສາໂປຣແກມ</p>
                                    </div>
                                </div>
                            </div>
                            <div class="box2">
                                <div class="content2">
                                    <div class="text">
                                        <p>ໂຄງສ້າງຂອງຄອມພິວເຕີ</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="c-lom">
                            <div class="box2">
                                <div class="content2">
                                    <div class="text">
                                        <p>ການພັດທະນາຊອບແວ</p>
                                    </div>
                                </div>
                            </div>
                            <div class="box2">
                                <div class="content2">
                                    <div class="text">
                                        <p>ການວິເຄາະລະບົບ ແລະ ໂຄງສ້າງຂໍ້ມູນ</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="c-lom">
                            <div class="box2">
                                <div class="content2">
                                    <div class="text">
                                        <p>ຖານຂໍ້ມູນ</p>
                                    </div>
                                </div>
                            </div>
                            <div class="box2">
                                <div class="content2">
                                    <div class="text">
                                        <p>ອອກແບບ ແລະ ພັດທະນາເວັບໄຊ</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="p-text">
                    <h1 class="h-t h2">ສະຖານະພາບການຈ້າງງານ ແລະ ສະຖານະພາບການເຮັດວຽກຫຼັງຈາກຮຽນຈົບ</h1>
                </div>
                <div class="opp2">
                    <p>ຖ້າຫາກທ່ານຈົບຈາກພາກວິຊານີ້, ທ່ານຈະສາມາດເຮັດວຽກໃນຂົງເຂດຕ່າງໆເຊັ່ນເປັນນັກຂຽນຊອບແວ, ພະນັກງານບໍລິການເຄືອຂ່າຍຄອມພິວເຕີ ແລະ ຜູ້ປະກອບການຄອມພິວເຕີ. ແລະທ່ານຍັງສາມາດຮຽນຮູ້ການອອກແບບລະບົບຄອມພິວເຕີ ແລະ ການພັດທະນາໂດຍຜ່ານຫຼັກສູດປະລິນຍາໂທ ແລະ ປະລິນຍາເອກ.
                    </p>
                </div>

                
                
                </section>
    
            </div>
            {% endblock %}

django-portfolio-main_lkc/mywebapp/templates/base.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
        
        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles1.css' %}">
       

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title>Lao-Korean College</title>
    </head>
    <body>
        <div class="container">
            <!--==================== HEADER ====================-->
            <header class="header">
                <nav class="nav ">
                    <a href="#" class="nav__logo">
                        <img src="{% static 'assets/img/logo.png' %}" alt="Educator Logo">
                    </a>
    
                    <div class="nav__menu" id="nav-menu">
                        <ul class="nav__list">
                            <li class="nav__item">
                                <a href="{% url 'index' %}" class="nav__link">ໜ້າຫຼັກ</a>
                            </li>
                            <li class="nav__item">
                                <a href="{% url 'about' %}" class="nav__link">ກ່ຽວກັບເຮົາ</a>
                            </li>
                            <li class="nav__item">
                                <a href="{% url 'teacher' %}" class="nav__link">ບັນດາອາຈານ</a>
                            </li>
                            <li class="nav__item">
                                <a href="{% url 'blog' %}" class="nav__link">ກິດຈະກຳພາຍໃນວິທະຍາໄລ</a>
                            </li>
                            <li class="nav__item">
                                <a href="#footer" class="nav__link">ຕິດຕໍ່ເຮົາ</a>
                            </li>
    
                        </ul>
    
    
    
                        <div class="nav__close" id="nav-close">
                            <i class='bx bx-x'></i>
                        </div>
                    </div>
                    <button class="button button--bestia">
                    <i id ="phon1"class="fa-solid fa-phone"></i>
                    <a href="tel:021-671-080"><div class="button__bg"></div><span>021-671-080</span></a>
                </button>
                    <!-- Toggle button -->
                    <div class="nav__toggle" id="nav-toggle">
                        <i class='bx bx-grid-alt'></i>
                    </div>
    
                </nav>
            </header>
            
                {% block content %}
                {% endblock %}
            </div>
            <div id="footer"></div>
            
    
            <footer>
    
                <div class="footer-grid">
    
                    <div class="grid-item">
    
                        <div class="footer-logo">
                            <img src="{% static 'assets/img/logo.png' %}" alt=" educator logo white ">
                        </div>
    
                        <p class="footer-text ">
                            ວິທະຍາໄລທີ່ໃຫ້ການບໍລິການແກ່ຄົນຍຸກໃໝ່ ແລະ ຊຸ່ມຊົນທີ່ຫ່າງໄກສອກຫຼີກ.
                        </p>
    
                        <div class="social-link">
                            <a href="https://www.facebook.com/AjanComprogram" target="_blank" class="i-1">
                                <i class="fa-brands fa-facebook-f"></i>
                            </a>
                            <a href="https://mail.google.com/mail/u/1/#inbox?compose=CllgCHrlFXxSVltzXzjLpfDNdcJmmxZMmfqNcphpnStfvpdxXdxQxBTfNqRmmSZNKqgMXvTKMrL" target="_blank" class="i-2">
                                <i class="fa-solid fa-envelope"></i>
                            </a>
                            <a href="tel:021-671-080" class="i-3">
                                <i class="fa-solid fa-phone"></i>
                            </a>
                            <a href="https://www.google.la/maps/place/Lao-Korean+College/@17.9930949,102.527826,17.52z/data=!4m5!3m4!1s0x31246a203983bf9d:0x4d940a4a295e8838!8m2!3d17.9931247!4d102.5278148?hl=ko" target="_blank" class="i-4">
                                <i class="fa-solid fa-location-dot"></i>
                            </a>
                        </div>
    
                    </div>
    
                    <ul class="grid-item ">
    
                        <h4 class="item-heading ">Our Link</h4>
    
                        <li class="list-item ">
                            <a href="http://lkclaos.org/" target="_blank">ວິທະຍາໄລລາວ-ເກົາຫຼີ</a>
                        </li>
    
                        <li class="list-item ">
                            <a href="http://lkclaos.org/%e0%ba%84%e0%ba%b3%e0%ba%97%e0%ba%b1%e0%ba%81%e0%ba%97%e0%ba%b2%e0%ba%8d%e0%ba%88%e0%ba%b2%e0%ba%81%e0%ba%9c%e0%ba%b9%e0%bb%89%e0%ba%ad%e0%ba%b3%e0%ba%99%e0%ba%a7%e0%ba%8d%e0%ba%81%e0%ba%b2/" target="_blank">ຄຳທັກທາຍຈາກຜູ້ອຳນວຍການ</a>
                        </li>
    
                        <li class="list-item ">
                            <a href="http://lkclaos.org/onlineregistration/" target="_blank">ລົງທະບຽນອອນລາຍ</a>
                        </li>
    
                        <li class="list-item ">
                            <a href="http://lkclaos.org/%e0%ba%9b%e0%ba%b0%e0%ba%ab%e0%ba%a7%e0%ba%b1%e0%ba%94%e0%ba%84%e0%ba%a7%e0%ba%b2%e0%ba%a1%e0%bb%80%e0%ba%9b%e0%ba%b1%e0%ba%99%e0%ba%a1%e0%ba%b2/" target="_blank">ປະຫວັດຄວາມເປັນມາ</a>
                        </li>
    
                        <li class="list-item ">
                            <a href="http://lkclaos.org/%e0%bb%80%e0%ba%88%e0%ba%b1%e0%ba%94%e0%ba%a5%e0%ba%b1%e0%ba%81%e0%ba%aa%e0%ba%b0%e0%ba%99%e0%ba%b0%e0%bb%80%e0%ba%94%e0%ba%b1%e0%bb%88%e0%ba%99%e0%ba%82%e0%ba%ad%e0%ba%87-lkc/" target="_blank">ເຈັດລັກສະນະເດັ່ນຂອງ LKC</a>
                        </li>
    
                    </ul>
                    <ul class="grid-item ">
    
                        <h4 class="item-heading " target="_blank">Our Link</h4>
    
                        <li class="list-item ">
                            <a href="http://lkclaos.org/%e0%bb%82%e0%ba%84%e0%ba%87%e0%ba%ae%e0%bb%88%e0%ba%b2%e0%ba%87%e0%ba%81%e0%ba%b2%e0%ba%99%e0%ba%88%e0%ba%b1%e0%ba%94%e0%ba%95%e0%ba%b1%e0%bb%89%e0%ba%87/" target="_blank">ໂຄງຮ່າງການຈັດຕັ້ງ</a>
                        </li>
    
                        <li class="list-item ">
                            <a href="http://lkclaos.org/%e0%ba%a5%e0%ba%b0%e0%ba%9a%e0%ba%bb%e0%ba%9a%e0%ba%97%e0%ba%b6%e0%ba%99%e0%ba%81%e0%ba%b2%e0%ba%99%e0%ba%aa%e0%ba%b6%e0%ba%81%e0%ba%aa%e0%ba%b2/" target="_blank">ລະບົບທຶນການສຶກສາ</a>
                        </li>
    
    
                        <li class="list-item ">
                            <a href="http://lkclaos.org/%e0%ba%ab%e0%ba%bc%e0%ba%b1%e0%ba%81%e0%ba%9b%e0%ba%b1%e0%ba%94%e0%ba%aa%e0%ba%b0%e0%ba%8d%e0%ba%b2-%e0%bb%81%e0%ba%a5%e0%ba%b0-%e0%bb%80%e0%ba%9b%e0%ba%bb%e0%bb%89%e0%ba%b2%e0%bb%9d%e0%ba%b2%e0%ba%8d/" target="_blank">ຫຼັກປັດສະຍາ ແລະ ເປົ້າໝາຍຂອງການສຶກສາ</a>
                        </li>
                        <li class="list-item ">
                            <a href="http://lkclaos.org/lao-%e0%ba%ad%e0%ba%bb%e0%ba%87%e0%ba%81%e0%ba%b2%e0%ba%99%e0%ba%ae%e0%bb%88%e0%ba%a7%e0%ba%a1%e0%ba%a1%e0%ba%b7%e0%ba%aa%e0%ba%b2%e0%ba%81%e0%ba%bb%e0%ba%99/" target="_blank">ອົງການຮ່ວມມືສາກົນ</a>
                        </li>
    
    
                    </ul>
                    <ul class="grid-item ">
    
                        <h4 class="item-heading ">ຕິດຕໍ່ສື່ສານ</h4>
    
                        <li class="list-item ">
                            <a href="https://mail.google.com/mail/u/1/#inbox?compose=CllgCHrlFXxSVltzXzjLpfDNdcJmmxZMmfqNcphpnStfvpdxXdxQxBTfNqRmmSZNKqgMXvTKMrL" target="_blank"><span class="list-item-color">E-mail:</span> laokoreancollege@gmail.com</a>
                        </li>
    
                        <li class="list-item ">
                            <a href="#footer"><span class="list-item-color">Address:</span> Phonsavathnuea Village, Sikhottabong <br> District, Vientiane Capital, Lao PDR.</a>
                        </li>
    
                        <li class="list-item ">
                            <a href="https://www.facebook.com/Lao-Korean-College-1472688249486161" target="_blank"><span class="list-item-color">Facebook:</span> lao-korean college</a>
                        </li>
                        <li class="list-item ">
                            <a href="https://www.facebook.com/AjanComprogram" target="_blank"><span class="list-item-color">Facebook:</span> Computer Program Development Centre of Lao Korean College</a>
                        </li>
    
    
                    </ul>
    
                </div>
            </footer>
        </div>

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/mainm.js' %}"></script>
        <script src="{% static 'assets/js/scrollreveal.min.js' %}"></script>
       
    </body>
</html>

django-portfolio-main_lkc/mywebapp/templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
                <hr>
    
                <div class="p-text" id="blog">
                    <h1 class="h-t">ກິດຈະກຳພາຍໃນໂຮງຮຽນ</h1>
                </div>
    
                <div class="container-img">

                    {% for category in categories %}
                        {% for picture in category.skills_set.all %}
                    <div class="item-img">
                        <div class="img-con-img">
                            <a href="http://lkclaos.org/lao-%e0%ba%81%e0%ba%b4%e0%ba%94%e0%ba%88%e0%ba%b0%e0%ba%81%e0%ba%b3%e0%ba%9e%e0%ba%b2%e0%ba%8d%e0%bb%83%e0%ba%99%e0%ba%a7%e0%ba%b4%e0%ba%97%e0%ba%b0%e0%ba%8d%e0%ba%b2%e0%bb%84%e0%ba%a5/">
                                <img src="{{ picture.skill_name.url }}" alt=""></a>
                        </div>
                    </div>
                        {% endfor %}
                    {% endfor %}
    
                </div>
    
                <div class="container-img">

                    {% for picture in blogs %}
                    
                    <div class="item-img">
                        <div class="img-con-img">
                            <a href="http://lkclaos.org/lao-%e0%ba%81%e0%ba%b4%e0%ba%94%e0%ba%88%e0%ba%b0%e0%ba%81%e0%ba%b3%e0%ba%9e%e0%ba%b2%e0%ba%8d%e0%bb%83%e0%ba%99%e0%ba%a7%e0%ba%b4%e0%ba%97%e0%ba%b0%e0%ba%8d%e0%ba%b2%e0%bb%84%e0%ba%a5/">
                                <img src="{{ picture.image.url }}" alt=""></a>
                        </div>
                    </div>
                    {% endfor %}
    
                </div>
                </section>
    
            </div>
            {% endblock %}

django-portfolio-main_lkc/mywebapp/templates/teacher.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    
                <div class="p-text" id="teacher">
                    <h1 class="h-t">ບັນດາອາຈານ</h1>
                    <h1 class="h-t">ປະຈຳພາກວິທະຍາສາດຄອມພິວເຕີ</h1>
                </div>
                <div class="grid1">

                    {% for portfolio in portfolios %}

                    <div class="grid-item1">

                        <img class="card-img1" src="{{ portfolio.image.url }}" alt="Rome" />
                        <div class="card-content1">
                            <h1 class="card-header1">{{ portfolio.link }}</h1>
                            
                        </div>
                    </div>
                    
                    {% endfor %}
                </div>
               <div class="grid1">

                    {% for pictures in portfolior %}

                    <div class="grid-item1">

                        <img class="card-img1" src="{{ pictures.image.url }}" alt="Rome" />
                        <div class="card-content1">
                            <h1 class="card-header1">{{ pictures.link }}</h1>
                            
                        </div>
                    </div>
                    
                    {% endfor %}
                </div>
                
                {% endblock %}
    
                
            